# Generated by Django 5.0.1 on 2024-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Query', models.CharField(max_length=200)),
                ('QueryEmail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SignupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=50)),
                ('confPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
